package jlogic.read;

public final class ReadException extends Exception {
    // This is apparently needed since Exceptions have to be serializable.
    // The number was generated by the compiler/eclipse.
    private static final long serialVersionUID = 5566180725053922759L;

    private final Location location;
    private final String message;

    public ReadException(Location location, String message) {
        this.location = location;
        this.message = message;
    }

    @Override
    public String toString() {
        return location.getLine() + "@" + location.getFile() + ": " + message;
    }

    public Location getLocation() {
        return location;
    }

    public String getMessage() {
        return message;
    }
}
